from . import product_template
from . import discount_code
from . import economic_activity
from . import res_company
from . import cajero
from . import account_move
from . import account_move_line
from . import config_settings
from . import documento_hacienda
from . import res_partner
from . import account_tax
from . import uom
from . import res_currency
